### ISSUE TITLE
Generate artifacts from CI

### ISSUE THREAD

**Issue by ethanl21** [Kynot54/tic-tac-toe-21#11]
It would benefit us to use a CI platform (probably GitHub Actions) to build and unit test our Godot project so that we always have an up to date prototype available and we have some quantitative metrics from unit tests.

Tasks include:
- [x] Making our Godot project exportable to our target platforms
- [x] Configuring GitHub Actions to build our project and store artifacts
- [x] #24

Blockers include:
- [x] Codesigning for iOS, I don't know if GitHub Actions can build ipa files from Xcode projects and they need to be signed using a developer key anyways
- [x] #23

We can have our project exported for web and uploaded to GitHub Pages for a web based preview, which may be necessary in case CI-based building for mobile platforms is impractical for this project.

**Comment by ethanl21** [comment]
It doesn't look like it's practical to build ipa files for iOS via cloud CI, so we'll do this manually when we need to demo.

**Comment by Kynot54** [comment]
Need to see if I can use git hub actions to do this for #23

**Comment by ethanl21** [comment]
Marking this as complete since #24 has been moved to a separate issue.
