### ISSUE TITLE
Build Android artifacts from CI

### ISSUE THREAD

**Issue by ethanl21** [Kynot54/tic-tac-toe-21#23]

**Comment by ethanl21** [comment]
(split from #11 )

We should configure our project to generate .apk files on each push to the main branch to always have an installable prototype available.

- [ ] Generate .apk from CI

I ran into some issue with a debug keystore when trying to build for the android emulator and I don't have an Android device to test on, so I don't have a way to figure this one out.

**Comment by Kynot54** [comment]
Made Android Deployment File .apk under my branch in folder labeled Android.

**Comment by Kynot54** [comment]
Will deploy a final .apk file to the release category once we have finished all changes.
