### ISSUE TITLE
Research and Implement a Finite State Machine

### ISSUE THREAD

**Issue by ethanl21** [Kynot54/tic-tac-toe-21#31]
We're required to deliver UML use case, class, and state diagrams for our project. We should implement the State pattern using a Finite State Machine for our game to meet the state requirement and keep our program's execution organized.

There's multiple plugins available to implement a FSM, so we should decide on which one to use. I'm looking at [this one](https://github.com/godot-addons/godot-finite-state-machine).

At minimum we should define whether the program is in the title screen, 21 scene, or tictactoe scene and assign state accordingly since the game can only be in one of those states at any moment.

**Comment by Kynot54** [comment]
We can do this for testing; however, I have been able to get the game functioning between scenes. 
What I have left is noted in #25 ...
