### ISSUE TITLE
Choose an decide on an algortihm slash method for the Dealer(AI) to play by for tic-tac-toe.

### ISSUE THREAD

**Issue by Kynot54** [Kynot54/tic-tac-toe-21#6]

**Comment by ethanl21** [comment]
I'll research playing tic tac toe with the Minimax algorithm. I'll need to keep in mind that a player can play for more than one turn in a row instead of alternating players like a normal game of tic tac toe.

**Comment by ethanl21** [comment]
#28 

I didn't end up using the minimax algorithm as that seemed overkill for this project.
